### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by XDqrkneZ** [UnityMCPE/HostgatorPower#1]
how to use

**Comment by xBeeegsone** [comment]
@XDqrkneZ , 
![image](https://user-images.githubusercontent.com/21226684/29492807-8bd146bc-8590-11e7-9ad1-490ef921255f.png)
1. Find Server's numeric ip-adress
2. Specify in the form IP-Address this numeric ip
3. Select count of threads (Depends on CPU cores / threads)
4. Click "start" button

**Comment by XDqrkneZ** [comment]
this may sound stupid, but where do you get that #HostgatorPo software?

**Comment by xBeeegsone** [comment]
@XDqrkneZ , this software was written by me ¯\_(ツ)_/¯.

**Comment by XDqrkneZ** [comment]
is it available for public or nahh

**Comment by xBeeegsone** [comment]
For public. But in the future I can release more "trahable" utilite.

**Comment by XDqrkneZ** [comment]
can i have link @xBeeegsone
